### ISSUE TITLE
Pnet version requires updating

### ISSUE THREAD

**Issue by varun19299** [j-jith/iitm-netaccess-cmd#1]
The cargo builds presently fail due to `pnet<=0.21`.
We changed the versions in the yaml file for our use case. 

Also, could a travis CI be setup for the cargo builds? (or similar)

Nice repo btw! Much better than the naive implementation we were using via barebones python.

**Comment by j-jith** [comment]
I haven't made any commits in a long while. Thanks for letting me know.
Please open a pull request with your modifications. I'll merge if it builds without issues.

Also, Travis CI has already been setup for this repo. I'm not sure what you mean.

**Comment by varun19299** [comment]
Sorry for the late reply. I've sent a pull request.

**Comment by j-jith** [comment]
Thank you. I'm closing the issue as I have already merged #2.
